version: "3.1"
services:
    firestore_emulator:
        image: mtlynch/firestore-emulator
        environment:
            - FIRESTORE_PROJECT_ID=demo-impera-widgets
            - PORT=8200
        ports:
            - 8200:8200
