name: Front tests

on:
    push:
        paths:
            - "apps/front/**"

jobs:
    run-tests:
        name: "Test front-end/server on push"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build and run Docker container
              run: |
                  docker compose -f compose.test.yml up -d --build
                  docker compose -f compose.test.yml exec front npm run test

            - name: Try to build app
              run: |
                  docker compose -f compose.test.yml exec front npm run build
                  
    # deploy:
    #     needs: run-tests
    #     runs-on: ubuntu-latest
    #     if: github.ref == 'refs/heads/master'
    #     steps:
    #         - name: Deploy to production
    #           run: |
    #               docker compose -f compose.prod.yml up -d --build